name: 'Dep script'
description: 'Install dependencies from other repos'

inputs:
  mint_version:
    description: 'The Mint version pull from (mint21, lmde5)'
    required: true
    default: mint21
  dependencies:
    description: 'A comma separated list of owner/repo dependencies to pull the latest build for (such as "linuxmint/xapp, linuxmint/cinnamon-desktop, linuxmint/cinnamon-menus")'
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        import sys
        import os
        import tempfile

        tag = "${{ inputs.mint_version }}"
        dep_string = os.environ["BUILD_DEPS"]
        if dep_string == "":
            exit(0)
        deps = dep_string.split(",")

        with tempfile.TemporaryDirectory() as dirname:
            for dep_entry in deps:
                dep_repo = dep_entry.strip()
                dep_name = dep_repo.split("/")[1]
                if os.system("wget https://github.com/%s/releases/download/master.%s/packages.tar.gz -O %s.tar.gz" % (dep_repo, tag, dep_name)) != 0:
                    exit(1)

            if os.system("ls *.tar.gz | xargs -i tar zxvf {}") != 0:
                exit(1)
            if os.system("sudo apt-get install --yes --allow-downgrades ./packages/*.deb") != 0:
                exit(1)
        exit(0)
      env:
        BUILD_DEPS: ${{ inputs.dependencies }}
      shell: python