name: Build

# called from a workflow in each repository
on:
  workflow_call:
    inputs:
      display_name:
        description: "Name of the build"
        required: true
        type: string
      mint_version:
        description: "The Mint version to tag for"
        required: true
        type: string
      image:
        description: "The container to build in"
        required: true
        type: string
      commit_id:
        description: "The commit sha or branch to build from"
        required: true
        default: "master"
        type: string
      dependencies:
        description: 'A comma separated list of owner/repo dependencies to pull the latest build for (such as "linuxmint/xapp, linuxmint/cinnamon-desktop, linuxmint/cinnamon-menus")'
        required: false
        type: string

jobs:
  build-on-image:
    name: ${{ inputs.display_name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      # Disable seccomp until a container manager in GitHub recognizes
      # clone3() syscall,
      # <https://github.com/actions/virtual-environments/issues/3812>.
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout Pull Request
        if: ${{ github.event_name == 'pull_request'}}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout branch ${{ github.ref }}
        if: ${{ github.event_name != 'pull_request'}}
        uses: actions/checkout@v3

      - name: Update build environment
        run: |
          echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
          sudo apt-get update
          sudo apt-get -y dist-upgrade
          sudo apt-get install -y python-is-python3
        shell: bash

      - name: Install first-class dependencies
        uses: linuxmint/github-actions/install-deps@master
        with:
          mint_version: ${{ inputs.mint_version }}
          dependencies: ${{ inputs.dependencies }}

      - name: Build
        uses: linuxmint/github-actions/real-build@master

      #### Stop here when triggered by a PR

      - name: Isolate packages
        if: ${{ github.event_name != 'pull_request'}}
        run: |
          mkdir -p ./output/packages
          mv ../*.deb ./output/packages
        shell: bash

      - name: Bundle packages
        if: ${{ github.event_name != 'pull_request'}}
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'tar'
          filename: 'packages.tar.gz'
          path: packages
          directory: ./output

      - name: Delete existing tag/release
        if: ${{ github.event_name != 'pull_request'}}
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ github.ref_name }}.${{ inputs.mint_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        if: ${{ github.event_name != 'pull_request'}}
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref_name }}.${{ inputs.mint_version }}
          prerelease: false
          files: "output/packages.tar.gz"
